site_name: pyparam
theme:
    name: 'material'
    font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
nav:
    - 'Introduction': 'index.md'
    - 'From command line arguments': 'fromCommandline.md'
    - 'Shell completions': 'shellCompletions.md'
    - 'Help page': 'helpPage.md'
    - 'From dict/configuration': 'fromDict.md'
    - 'Subcommands': 'commands.md'
    - 'Using the values': 'useTheValues.md'
    - 'Change log': 'changeLog.md'